server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dmg0020/springcloud-config-dmg-2020.git  #GitHub上的git仓库名字
          search-paths: springcloud-config-dmg-2020  #搜索目录
          skip-ssl-validation: true  #防止使用https请求的时候报错
        label: master #读取分支 默认分支，访问的时候不注明分支时会访问这个
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    register-with-eureka: true  #注册到Eureka
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka   #Eureka服务的地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #Eureka服务的地址

#暴漏bus刷新配置的断点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
