server:
  port: 7002


eureka:
  instance:
    hostname: eureka7002.com  #对外暴露地址 修改window电脑中的hosts文件，已经将 eureka服务端的实例名字
  client:
    register-with-eureka: false   #表识不向注册中心注册自己（相当于物业公司不和自己收物业费）
    fetch-registry: false  #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/   #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址