server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        # 配置之后，不能直接访问8001，而是要通过9527进行路由访问8001
      - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001   #匹配后提供服务的路由地址
        uri: lb://CLOUD-PAYMENT-SERVICE   #根据微服务名称进行负载均衡的地址
        predicates:
        - Path=/payment/get/**   #断言,路径相匹配的进行路由

      - id: payment_routh2
        #uri: http://localhost:8001
        uri: lb://CLOUD-PAYMENT-SERVICE   #根据微服务名称进行负载均衡的地址
        predicates:
        - Path=/payment/lb/**   #断言,路径相匹配的进行路由
        - After=2020-10-14T20:20:11.715+08:00[Asia/Shanghai] #在该时间之后，访问lb才有效果
        - Cookie=username,zzyy
        - Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性，并且值为正整数
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #Eureka服务的地址